apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: backend-service
  labels:
    app: backend
spec:
  # Choose how to expose your service
  ports:
    # The port number to expose the service
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: backend-port
  # Pod to route service traffic  
  selector:
    app: backend