apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: backend
  labels:
    app: backend
spec:
  # Choose how to expose your service
  type: ClusterIP
  ports:
    # The port number to expose the service
    - port: 5432
      protocol: TCP
    - port: 3000
      protocol: TCP
  # Pod to route service traffic
  selector:
    app: backend