# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  # The name of the Deployment
  name: backend
spec:
  # Replicas for this Deployment
  replicas: 1
  selector:
    # labels the podsmc
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: backend
    spec:
      containers:
        # The container name to execute pods
        - name: backend
          # pull postgresimage from docker hub
          image: maxcxam/itea_backend
          ports:
            # Assign ports to expose container
            - containerPort: 5432
            - containerPort: 3000