apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: frontend-service
  labels:
    app: frontend
spec:
  # Choose how to expose your service
  ports:
    # The port number to expose the service
    - port: 80
      targetPort: 80
      protocol: TCP
      name: frontend-port
       # Pod to route service traffic  
  selector:
    app: frontend