apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: frontend
  labels:
    app: frontend
spec:
  # Choose how to expose your service
  type: ClusterIP
  ports:
    # The port number to expose the service
    - port: 80
      targetPort: 8080
    - port: 3000
  # Pod to route service traffic  
  selector:
    app: frontend