apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: {{ .Values.backend_service.name }}-service
  labels:
    app: {{ .Values.backend.name }}
spec:
  # Choose how to expose your service
  ports:
    # The port number to expose the service
    - port: {{ .Values.backend_service.port }}
      targetPort: {{ .Values.backend_service.targetPort }}
      protocol: TCP
      name: {{ .Values.backend_service.name }}-port
  # Pod to route service traffic  
  selector:
    app: {{ .Values.backend.name }}