# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  # The name of the Deployment
  name: {{ .Values.backend.name }}-deployment
spec:
  # Replicas for this Deployment
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    # labels the podsmc
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: {{ .Values.backend.name }}
    spec:
      containers:
        # The container name to execute pods
        - name: {{ .Values.backend.name }}
          # pull postgresimage from docker hub
          image: {{ .Values.backend.image.repository }}
          ports:
            # Assign ports to expose container
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "mydb"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: "mydb"
            - name: PGHOST
              value:  "db-service"