apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: {{ .Values.database_service.name }}-service
  labels:
    app: {{ .Values.database.name }}
spec:
  # Choose how to expose your service
  ports:
    # The port number to expose the service
    - port: {{ .Values.database_service.port }}
  # Pod to route service traffic  
  selector:
    app: {{ .Values.database.name }}