# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  # The name of the Deployment
  name: {{ .Values.frontend.name }}-deployment
spec:
  # Replicas for this Deployment
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    # labels the pods
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: {{ .Values.frontend.name }}
    spec:
      containers:
        # The container name to execute pods
        - name: {{ .Values.frontend.name }}
          # pull postgresimage from docker hub
          image: {{ .Values.frontend.image.repository }}
          ports:
            # Assign ports to expose container
            - containerPort: {{ .Values.frontend.port }}