{{- if .Values.autoscaling.enabled }}
apiVersion: autoscalling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    name: {{ .Values.frontend.name}}-autoscaling
    spec:
        scaleTargetRef:
            apiVersion: apps/v2beta1
            kind: Deployment
            name: {{ .Values.frontend.name}}
        minReplicas: {{ .Values.autoscaling.minReplicas }}
        maxReplicas: {{ .Values.autoscaling.maxReplicas }}
        metrics:
        - type: Resource
          resource:
            name: cpu
            targetAveregeUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
        - type: Resource
          resource:
            name: memory
            targetAveregeUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}