apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: {{ .Values.frontend_service.name}}-service
  labels:
    app: {{ .Values.frontend.name}}
spec:
  # Choose how to expose your service
  ports:
    # The port number to expose the service
    - port: {{ .Values.frontend_service.port }}
      targetPort: {{ .Values.frontend_service.targetPort }}
      protocol: TCP
      name: {{ .Values.frontend_service.name }}-port
       # Pod to route service traffic  
  selector:
    app: {{ .Values.frontend.name}}